### ISSUE TITLE
Code Review rbtree.rg.h

### ISSUE THREAD

**Issue by sliverc** [ganwell/rbtree#1]
@ganwell 
As discussed I looked through the rbtree header file and here some comments on it:

https://github.com/ganwell/rbtree/blob/master/src/rbtree.rg.h#L104
What does the _m postfix stand for?

https://github.com/ganwell/rbtree/blob/master/src/rbtree.rg.h#L145
I have a feeling this method is documented a bit late as when I was passing
through the documentation I was always wondering - where is this `bk_` coming from...
Maybe comparator should only be explained once `rb_bind_impl_m` is explained.

**Comment by ganwell** [comment]
@sliverc updated in c7ae3b0

**Comment by sliverc** [comment]
Looks good. Closing this issue.
